/**
 * PageRank1.0
 * 说明：
 * 最大数量：爬虫爬取的网页数量最大值
 * 超时：对于每个网页，超过设定时间无响应后爬虫将自动断开连接
 * 运行：爬虫+PageRank
 * 跳过爬虫运行：仅PageRank，使用上次爬虫运行的结果
 * 初始页面：以一个包括nju.edu.cn的链接为起始页面
 * 
 * 生成文件：“院系链接关系.txt”(两行代表一个指向关系，一行为原网页一行为目标网页)、
 * “院系所有链接.txt”（每个涉及到的网页占一行）、
 * “链接数.txt”（一个数字，代表上次运行爬虫爬取的网页数）
 * “pagerank结果.txt”（pagerank运算结果）
 */
package PageRank;

import ch.randelshofer.quaqua.util.Methods;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.LineNumberReader;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author oubeichen
 */
public class MainFrame extends javax.swing.JFrame {

    static void setprogress(int num, String url) {//显示百分比
        jTextArea1.setText("Progressing...." + num + " of " + max + "\n" + url);
        jTextArea1.paintImmediately(jTextArea1.getX(), jTextArea1.getY(), jTextArea1.getWidth(), jTextArea1.getHeight());
        SwingUtilities.invokeLater(run);
    }

    static void settext(String str) {//显示文字
        jTextArea1.setText(str);
        jTextArea1.paintImmediately(jTextArea1.getX(), jTextArea1.getY(), jTextArea1.getWidth(), jTextArea1.getHeight());
    }

    static void appendaline(String str) {//串接文字
        jTextArea1.append(str + "\n");
        //jTextArea1.paintImmediately(jTextArea1.getX(), jTextArea1.getY(), jTextArea1.getWidth(), jTextArea1.getHeight());
    }

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        jTextArea1.setText("");
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();//设置显示在屏幕正中
        Dimension frameSize = getSize();
        setLocation(new Point((screenSize.width - frameSize.width) / 2,
                (screenSize.height - frameSize.width) / 2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PageRank");
        setLocationByPlatform(true);

        jButton1.setText("运行");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("宋体", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("最大数量:");

        jButton2.setText("跳过爬虫运行");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("超时:");

        jTextField2.setText("1000");

        jLabel3.setText("ms");

        jLabel4.setText("初始页面: http://");

        jTextField3.setText("www.nju.edu.cn");

        jMenu1.setText("文件");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("运行");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("跳过爬虫运行");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem4.setText("退出");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("帮助");

        jMenuItem2.setText("关于");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        AboutDialog addd = new AboutDialog(this, true);
        addd.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void go() {//运行的后台线程
        //删除文件，初始化
        jTextArea1.setText("");//清空显示
        try {
            max = Integer.parseInt(jTextField1.getText().toString());
            timeout = Integer.parseInt(jTextField2.getText().toString());
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "请输入数字！！", "输入错误", javax.swing.JOptionPane.ERROR_MESSAGE);
            t = null;
            return;

        } //输入非数字
        if (!jTextField3.getText().contains(".nju.edu.cn")) {
            javax.swing.JOptionPane.showMessageDialog(this, "必须是南大的链接！！", "输入错误", javax.swing.JOptionPane.ERROR_MESSAGE);
            t = null;
            return;
        }//输入非南大链接
        try {
            //重新开始之前的初始化开始
            newcrawler.clear(max, timeout);
            pagerank.clear(max);
            new File("院系链接关系.txt").delete();
            new File("院系所有链接.txt").delete();
            new File("链接数.txt").delete();
            new File("pagerank结果.txt").delete();
            //重新开始之前的初始化结束
            newcrawler.MyCrawler.crawling(new String[]{"http://" + jTextField3.getText()});
            FileWriter fwall = new FileWriter("院系所有链接.txt", false);
            for (String Visitedlink : newcrawler.LinkQueue.getVisitedUrl()) {
                fwall.write(Visitedlink + "\n");
            }
            fwall.close();

            pagerank.setHashMap();
            pagerank.setLinks();
            pagerank.doPageRank();
            pagerank.outputResult();

            FileWriter fwcnt = new FileWriter("链接数.txt", false);//输出上次爬虫的链接数，为后面pagerank做准备
            fwcnt.write(Integer.toString(max));
            fwcnt.close();

        } catch (IOException ex) {
            jTextArea1.setText("文件操作有误！");
        }
        t = null;
    }

    class GoThread extends Thread {

        public void run() {//每个线程都运行go这个函数 
            go();
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (t == null) {//新建函数来后台爬虫
            t = new GoThread();
            t.start();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        jButton1ActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        jButton2ActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            if (new File("院系链接关系.txt").exists() && new File("院系所有链接.txt").exists() && new File("链接数.txt").exists()) {
            } else //说明文件不存在，尚未运行过爬虫
            {
                javax.swing.JOptionPane.showMessageDialog(this, "尚未运行过爬虫，请点击Run按钮运行！", "操作错误", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            FileReader fr = new FileReader(new File("链接数.txt"));
            LineNumberReader lr = new LineNumberReader(fr);
            max = Integer.parseInt(lr.readLine().toString());
            pagerank.clear(max);
            pagerank.setHashMap();
            pagerank.setLinks();
            pagerank.doPageRank();
            pagerank.outputResult();
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //</editor-fold>
        //==========================外观皮肤设置开始======================
        // set system properties here that affect Quaqua
        if (!System.getProperty("os.name").toLowerCase().startsWith("mac")) {
            try {
                Methods.invokeStatic(JFrame.class, "setDefaultLookAndFeelDecorated", Boolean.TYPE, Boolean.TRUE);
                Methods.invokeStatic(JDialog.class, "setDefaultLookAndFeelDecorated", Boolean.TYPE, Boolean.TRUE);
            } catch (NoSuchMethodException e) {
                e.printStackTrace();
            }
        }
        // set the Quaqua Look and Feel in the UIManager
        try {
            setDefaultLookAndFeelDecorated(true);
            UIManager.setLookAndFeel(ch.randelshofer.quaqua.QuaquaManager.getLookAndFeel());
            // set UI manager properties here that affect Quaqua
        } catch (Exception e) {
            // take an appropriate action here
            System.err.println("Oops!  Something went wrong!");
        }
        //==========================外观皮肤设置结束======================
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    static int max = 139;
    static int timeout = 1000;
    private GoThread t = null;
    static private Runnable run = null;//更新组件的线程
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
